spring.sql.init.mode=always

police.lost-item.sync.enabled=true
police.lost-item.backfill-on-startup=true

police.found-item.sync.enabled=true
police.found-item.backfill-on-startup=true

spring.mail.properties.mail.debug=true

admin.password=${ADMIN_PASSWORD:admin1234}
