CREATE TABLE IF NOT EXISTS USERS (
  USER_NO BIGINT AUTO_INCREMENT PRIMARY KEY,
  LOGIN_ID VARCHAR(100) UNIQUE,
  PASSWORD VARCHAR(255),
  EMAIL VARCHAR(255) UNIQUE,
  NICKNAME VARCHAR(50),
  PHONE VARCHAR(30),
  PROFILE_IMAGE_URL VARCHAR(500),
  ROLE VARCHAR(30) NOT NULL DEFAULT 'USER',
  STATUS VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',
  REGDATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  MODDATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS USER_SOCIAL_ACCOUNT (
  SOCIAL_ACCOUNT_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  USER_NO BIGINT NOT NULL,
  PROVIDER VARCHAR(30) NOT NULL,
  PROVIDER_USER_ID VARCHAR(255) NOT NULL,
  EMAIL VARCHAR(255),
  NICKNAME VARCHAR(50),
  PROFILE_IMAGE_URL VARCHAR(500),
  REGDATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  MODDATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

  CONSTRAINT FK_SOCIAL_USER
    FOREIGN KEY (USER_NO) REFERENCES USERS(USER_NO),

  UNIQUE KEY UK_SOCIAL_PROVIDER_USER (PROVIDER, PROVIDER_USER_ID),
  UNIQUE KEY UK_USER_PROVIDER (USER_NO, PROVIDER)
);

CREATE TABLE IF NOT EXISTS CATEGORY (
  CATEGORY_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  CATEGORY_NAME VARCHAR(100) NOT NULL,
  CATEGORY_CODE VARCHAR(30),
  PARENT_CATEGORY_ID BIGINT,
  LEVEL INT NOT NULL,
  SORT_ORDER INT NOT NULL DEFAULT 0,
  IS_ACTIVE BOOLEAN NOT NULL DEFAULT TRUE,

  CONSTRAINT FK_CATEGORY_PARENT
    FOREIGN KEY (PARENT_CATEGORY_ID) REFERENCES CATEGORY(CATEGORY_ID)
);

INSERT INTO CATEGORY (CATEGORY_NAME, CATEGORY_CODE, PARENT_CATEGORY_ID, LEVEL, SORT_ORDER, IS_ACTIVE)
SELECT '지갑', 'WALLET', NULL, 1, 10, TRUE
WHERE NOT EXISTS (SELECT 1 FROM CATEGORY WHERE CATEGORY_CODE = 'WALLET');

INSERT INTO CATEGORY (CATEGORY_NAME, CATEGORY_CODE, PARENT_CATEGORY_ID, LEVEL, SORT_ORDER, IS_ACTIVE)
SELECT '가방', 'BAG', NULL, 1, 20, TRUE
WHERE NOT EXISTS (SELECT 1 FROM CATEGORY WHERE CATEGORY_CODE = 'BAG');

INSERT INTO CATEGORY (CATEGORY_NAME, CATEGORY_CODE, PARENT_CATEGORY_ID, LEVEL, SORT_ORDER, IS_ACTIVE)
SELECT '전자기기', 'ELECTRONICS', NULL, 1, 30, TRUE
WHERE NOT EXISTS (SELECT 1 FROM CATEGORY WHERE CATEGORY_CODE = 'ELECTRONICS');

INSERT INTO CATEGORY (CATEGORY_NAME, CATEGORY_CODE, PARENT_CATEGORY_ID, LEVEL, SORT_ORDER, IS_ACTIVE)
SELECT '의류', 'CLOTHING', NULL, 1, 40, TRUE
WHERE NOT EXISTS (SELECT 1 FROM CATEGORY WHERE CATEGORY_CODE = 'CLOTHING');

INSERT INTO CATEGORY (CATEGORY_NAME, CATEGORY_CODE, PARENT_CATEGORY_ID, LEVEL, SORT_ORDER, IS_ACTIVE)
SELECT '기타', 'ETC', NULL, 1, 50, TRUE
WHERE NOT EXISTS (SELECT 1 FROM CATEGORY WHERE CATEGORY_CODE = 'ETC');

CREATE TABLE IF NOT EXISTS AREA (
  AREA_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  AREA_NAME VARCHAR(100) NOT NULL,
  AREA_CODE VARCHAR(30),
  PARENT_AREA_ID BIGINT,
  SORT_ORDER INT NOT NULL DEFAULT 0,
  IS_ACTIVE BOOLEAN NOT NULL DEFAULT TRUE,
  LATITUDE DECIMAL(10,7),
  LONGITUDE DECIMAL(10,7),
  DEFAULT_LEVEL INT NOT NULL DEFAULT 4,

  CONSTRAINT FK_AREA_PARENT
    FOREIGN KEY (PARENT_AREA_ID) REFERENCES AREA(AREA_ID)
);

CREATE TABLE IF NOT EXISTS police_station (
  pnu VARCHAR(19) PRIMARY KEY,
  longitude DOUBLE NOT NULL,
  latitude DOUBLE NOT NULL,
  address VARCHAR(1000),
  address1 VARCHAR(1000) NOT NULL,
  no_value INT NOT NULL,
  lclsf VARCHAR(10) NOT NULL,
  cmptnc_rgn_nm VARCHAR(40) NOT NULL,
  polstn_nm VARCHAR(20) NOT NULL,
  se VARCHAR(20) NOT NULL,
  telno VARCHAR(20) NOT NULL,
  addr VARCHAR(200) NOT NULL
);

CREATE TABLE IF NOT EXISTS LOST_ITEM (
  LOST_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  USER_NO BIGINT,
  SOURCE_TYPE VARCHAR(30) NOT NULL DEFAULT 'USER',
  ATC_ID VARCHAR(20),
  TITLE VARCHAR(300) NOT NULL,
  CONTENT TEXT,
  ITEM_NAME VARCHAR(500) NOT NULL,
  CATEGORY_ID BIGINT,
  CATEGORY_MAIN VARCHAR(100),
  CATEGORY_SUB VARCHAR(100),
  COLOR_NAME VARCHAR(100),
  LOST_AT DATETIME NOT NULL,
  LOST_AREA VARCHAR(100),
  LOST_PLACE VARCHAR(500) NOT NULL,
  CONTACT VARCHAR(100),
  STATUS VARCHAR(30) NOT NULL DEFAULT 'WAITING',
  IS_DELETED BOOLEAN NOT NULL DEFAULT FALSE,
  REGDATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  MODDATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

  CONSTRAINT FK_LOST_ITEM_USER
    FOREIGN KEY (USER_NO) REFERENCES USERS(USER_NO),

  CONSTRAINT FK_LOST_ITEM_CATEGORY
    FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORY(CATEGORY_ID),

  CONSTRAINT CK_LOST_SOURCE
    CHECK (
      (SOURCE_TYPE = 'USER' AND USER_NO IS NOT NULL AND ATC_ID IS NULL)
      OR
      (SOURCE_TYPE = 'POLICE' AND ATC_ID IS NOT NULL)
    ),

  UNIQUE KEY UK_POLICE_LOST_ITEM (ATC_ID),
  INDEX IDX_LOST_SEARCH (SOURCE_TYPE, CATEGORY_MAIN, LOST_AT, STATUS),
  INDEX IDX_LOST_USER (USER_NO),
  INDEX IDX_LOST_ATC_ID (ATC_ID)
);

CREATE TABLE IF NOT EXISTS LOST_ITEM_IMAGE (
  IMAGE_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  LOST_ID BIGINT NOT NULL,
  ORIGINAL_NAME VARCHAR(255),
  STORED_NAME VARCHAR(255) NOT NULL,
  IMAGE_URL VARCHAR(500) NOT NULL,
  CONTENT_TYPE VARCHAR(100),
  FILE_SIZE BIGINT,
  SORT_ORDER INT NOT NULL DEFAULT 0,
  REGDATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

  CONSTRAINT FK_LOST_IMAGE_ITEM
    FOREIGN KEY (LOST_ID) REFERENCES LOST_ITEM(LOST_ID)
    ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS FOUND_ITEM (
  FOUND_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  USER_NO BIGINT,
  SOURCE_TYPE VARCHAR(30) NOT NULL DEFAULT 'USER',
  ATC_ID VARCHAR(20),
  FD_SN INT,
  TITLE VARCHAR(300),
  CONTENT TEXT,
  ITEM_NAME VARCHAR(200) NOT NULL,
  CATEGORY_ID BIGINT,
  CATEGORY_MAIN VARCHAR(100),
  CATEGORY_SUB VARCHAR(100),
  COLOR_NAME VARCHAR(100),
  FOUND_AT DATETIME NOT NULL,
  FOUND_AREA VARCHAR(100),
  FOUND_PLACE VARCHAR(255),
  KEEP_PLACE VARCHAR(255),
  CONTACT VARCHAR(100),
  CUSTODY_STATUS VARCHAR(50),
  RECEIVE_TYPE VARCHAR(50),
  MANAGE_NO VARCHAR(100),
  SERIAL_NO VARCHAR(100),
  MODEL_CODE VARCHAR(100),
  IMEI VARCHAR(100),
  OWNER_NAME VARCHAR(100),
  STATUS VARCHAR(30) NOT NULL DEFAULT 'KEEPING',
  IS_DELETED BOOLEAN NOT NULL DEFAULT FALSE,
  REGDATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  MODDATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

  CONSTRAINT FK_FOUND_ITEM_USER
    FOREIGN KEY (USER_NO) REFERENCES USERS(USER_NO),

  CONSTRAINT FK_FOUND_ITEM_CATEGORY
    FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORY(CATEGORY_ID),

  CONSTRAINT CK_FOUND_SOURCE
    CHECK (
      (SOURCE_TYPE = 'USER' AND USER_NO IS NOT NULL AND ATC_ID IS NULL AND FD_SN IS NULL)
      OR
      (SOURCE_TYPE = 'POLICE' AND ATC_ID IS NOT NULL AND FD_SN IS NOT NULL)
    ),

  UNIQUE KEY UK_POLICE_FOUND_ITEM (ATC_ID, FD_SN),
  INDEX IDX_FOUND_SEARCH (SOURCE_TYPE, CATEGORY_MAIN, FOUND_AT, STATUS),
  INDEX IDX_FOUND_USER (USER_NO),
  INDEX IDX_FOUND_ATC_ID (ATC_ID)
);

CREATE TABLE IF NOT EXISTS FOUND_ITEM_IMAGE (
  IMAGE_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  FOUND_ID BIGINT NOT NULL,
  ORIGINAL_NAME VARCHAR(255),
  STORED_NAME VARCHAR(255),
  IMAGE_URL VARCHAR(600) NOT NULL,
  CONTENT_TYPE VARCHAR(100),
  FILE_SIZE BIGINT,
  SORT_ORDER INT NOT NULL DEFAULT 0,
  REGDATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

  CONSTRAINT FK_FOUND_IMAGE_ITEM
    FOREIGN KEY (FOUND_ID) REFERENCES FOUND_ITEM(FOUND_ID)
    ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS ITEM_MATCH (
  MATCH_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  LOST_ID BIGINT NOT NULL,
  FOUND_ID BIGINT NOT NULL,
  MATCH_SCORE DECIMAL(5,2),
  MATCH_STATUS VARCHAR(30) NOT NULL DEFAULT 'CANDIDATE',
  REGDATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  MODDATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

  CONSTRAINT FK_MATCH_LOST
    FOREIGN KEY (LOST_ID) REFERENCES LOST_ITEM(LOST_ID),

  CONSTRAINT FK_MATCH_FOUND
    FOREIGN KEY (FOUND_ID) REFERENCES FOUND_ITEM(FOUND_ID),

  UNIQUE KEY UK_MATCH_LOST_FOUND (LOST_ID, FOUND_ID)
);

CREATE TABLE IF NOT EXISTS SERVICE_CENTER (
  CENTER_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  CENTER_NAME VARCHAR(100) NOT NULL,
  ADDRESS VARCHAR(255),
  PHONE VARCHAR(30),
  OPEN_TIME VARCHAR(100),
  LATITUDE DECIMAL(10,7),
  LONGITUDE DECIMAL(10,7),
  REGDATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  MODDATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS INQUIRY (
INQUIRY_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
USER_NO BIGINT,
CATEGORY VARCHAR(20) NOT NULL,
TITLE VARCHAR(200) NOT NULL,
CONTENT TEXT NOT NULL,
STATUS VARCHAR(30) NOT NULL DEFAULT 'UNREAD',
ANSWER TEXT,
ANSWERED_AT DATETIME,
REGDATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
MODDATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

CONSTRAINT FK_INQUIRY_USER FOREIGN KEY (USER_NO) REFERENCES USERS(USER_NO),
CONSTRAINT CK_INQUIRY_CATEGORY CHECK (CATEGORY IN ('분실물','습득물','서비스','기타')),
CONSTRAINT CK_INQUIRY_STATUS CHECK (STATUS IN ('UNREAD','CHECKING','ANSWERED'))
);

CREATE TABLE IF NOT EXISTS INQUIRY_FILE (
FILE_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
INQUIRY_ID BIGINT NOT NULL,
ORIGINAL_NAME VARCHAR(255) NOT NULL,
STORED_NAME VARCHAR(255) NOT NULL,
FILE_URL VARCHAR(500) NOT NULL,
CONTENT_TYPE VARCHAR(100),
FILE_SIZE BIGINT,
REGDATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

CONSTRAINT FK_INQUIRY_FILE FOREIGN KEY (INQUIRY_ID)
REFERENCES INQUIRY(INQUIRY_ID) ON DELETE CASCADE
);


DROP TABLE IF EXISTS korail_station_location;
CREATE TABLE korail_station_location (
  station_id BIGINT AUTO_INCREMENT PRIMARY KEY,
  line_name VARCHAR(50) NOT NULL,
  station_name VARCHAR(100) NOT NULL,
  latitude DOUBLE NOT NULL,
  longitude DOUBLE NOT NULL,
  exit_count INT,
  INDEX idx_station_lookup (station_name, line_name)
);

DROP TABLE IF EXISTS korail_lost_found_center;
CREATE TABLE korail_lost_found_center (
  center_id BIGINT AUTO_INCREMENT PRIMARY KEY,
  operator_name VARCHAR(100),
  line_name VARCHAR(50),
  station_name VARCHAR(100) NOT NULL,
  location_details VARCHAR(500),
  operating_hours VARCHAR(200),
  tel_no VARCHAR(50),
  INDEX idx_lost_found_station (station_name, line_name)
);
