CREATE TABLE IF NOT EXISTS USERS (
  USER_NO BIGINT AUTO_INCREMENT PRIMARY KEY,
  LOGIN_ID VARCHAR(100) UNIQUE,
  PASSWORD VARCHAR(255),
  EMAIL VARCHAR(255) UNIQUE,
  NICKNAME VARCHAR(50),
  PHONE VARCHAR(30),
  PROFILE_IMAGE_URL VARCHAR(500),
  ROLE VARCHAR(30) NOT NULL DEFAULT 'USER',
  STATUS VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',
  REGDATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  MODDATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  WITHDRAWN_AT DATETIME NULL
);

CREATE TABLE IF NOT EXISTS USER_SOCIAL_ACCOUNT (
  SOCIAL_ACCOUNT_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  USER_NO BIGINT NOT NULL,
  PROVIDER VARCHAR(30) NOT NULL,
  PROVIDER_USER_ID VARCHAR(255) NOT NULL,
  EMAIL VARCHAR(255),
  NICKNAME VARCHAR(50),
  PROFILE_IMAGE_URL VARCHAR(500),
  REGDATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  MODDATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

  CONSTRAINT FK_SOCIAL_USER
    FOREIGN KEY (USER_NO) REFERENCES USERS(USER_NO),

  UNIQUE KEY UK_SOCIAL_PROVIDER_USER (PROVIDER, PROVIDER_USER_ID),
  UNIQUE KEY UK_USER_PROVIDER (USER_NO, PROVIDER)
);

CREATE TABLE IF NOT EXISTS CATEGORY (
  CATEGORY_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  CATEGORY_NAME VARCHAR(100) NOT NULL,
  CATEGORY_CODE VARCHAR(30),
  PARENT_CATEGORY_ID BIGINT,
  LEVEL INT NOT NULL,
  SORT_ORDER INT NOT NULL DEFAULT 0,
  IS_ACTIVE BOOLEAN NOT NULL DEFAULT TRUE,

  CONSTRAINT FK_CATEGORY_PARENT
    FOREIGN KEY (PARENT_CATEGORY_ID) REFERENCES CATEGORY(CATEGORY_ID)
);

INSERT INTO CATEGORY (CATEGORY_NAME, CATEGORY_CODE, PARENT_CATEGORY_ID, LEVEL, SORT_ORDER, IS_ACTIVE)
SELECT '지갑', 'WALLET', NULL, 1, 10, TRUE
WHERE NOT EXISTS (SELECT 1 FROM CATEGORY WHERE CATEGORY_CODE = 'WALLET');

INSERT INTO CATEGORY (CATEGORY_NAME, CATEGORY_CODE, PARENT_CATEGORY_ID, LEVEL, SORT_ORDER, IS_ACTIVE)
SELECT '가방', 'BAG', NULL, 1, 20, TRUE
WHERE NOT EXISTS (SELECT 1 FROM CATEGORY WHERE CATEGORY_CODE = 'BAG');

INSERT INTO CATEGORY (CATEGORY_NAME, CATEGORY_CODE, PARENT_CATEGORY_ID, LEVEL, SORT_ORDER, IS_ACTIVE)
SELECT '전자기기', 'ELECTRONICS', NULL, 1, 30, TRUE
WHERE NOT EXISTS (SELECT 1 FROM CATEGORY WHERE CATEGORY_CODE = 'ELECTRONICS');

INSERT INTO CATEGORY (CATEGORY_NAME, CATEGORY_CODE, PARENT_CATEGORY_ID, LEVEL, SORT_ORDER, IS_ACTIVE)
SELECT '의류', 'CLOTHING', NULL, 1, 40, TRUE
WHERE NOT EXISTS (SELECT 1 FROM CATEGORY WHERE CATEGORY_CODE = 'CLOTHING');

INSERT INTO CATEGORY (CATEGORY_NAME, CATEGORY_CODE, PARENT_CATEGORY_ID, LEVEL, SORT_ORDER, IS_ACTIVE)
SELECT '기타', 'ETC', NULL, 1, 50, TRUE
WHERE NOT EXISTS (SELECT 1 FROM CATEGORY WHERE CATEGORY_CODE = 'ETC');

CREATE TABLE IF NOT EXISTS AREA (
  AREA_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  AREA_NAME VARCHAR(100) NOT NULL,
  AREA_CODE VARCHAR(30),
  PARENT_AREA_ID BIGINT,
  SORT_ORDER INT NOT NULL DEFAULT 0,
  IS_ACTIVE BOOLEAN NOT NULL DEFAULT TRUE,
  LATITUDE DECIMAL(10,7),
  LONGITUDE DECIMAL(10,7),
  DEFAULT_LEVEL INT NOT NULL DEFAULT 4,

  CONSTRAINT FK_AREA_PARENT
    FOREIGN KEY (PARENT_AREA_ID) REFERENCES AREA(AREA_ID)
);

CREATE TABLE IF NOT EXISTS police_station (
  pnu VARCHAR(19) PRIMARY KEY,
  longitude DOUBLE NOT NULL,
  latitude DOUBLE NOT NULL,
  address VARCHAR(1000),
  address1 VARCHAR(1000) NOT NULL,
  no_value INT NOT NULL,
  lclsf VARCHAR(10) NOT NULL,
  cmptnc_rgn_nm VARCHAR(40) NOT NULL,
  polstn_nm VARCHAR(20) NOT NULL,
  se VARCHAR(20) NOT NULL,
  telno VARCHAR(20) NOT NULL,
  addr VARCHAR(200) NOT NULL
);

CREATE TABLE IF NOT EXISTS subway_lost_center (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  operator_name VARCHAR(100),
  line_name VARCHAR(50),
  region VARCHAR(100),
  sub_region VARCHAR(100),
  station_name VARCHAR(100) NOT NULL,
  latitude DOUBLE,
  longitude DOUBLE,
  detail_location VARCHAR(500),
  available_time VARCHAR(100),
  tel_no VARCHAR(50),
  REGDATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  MODDATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS LOST_ITEM (
  LOST_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  USER_NO BIGINT,
  SOURCE_TYPE VARCHAR(30) NOT NULL DEFAULT 'USER',
  ATC_ID VARCHAR(20),
  TITLE VARCHAR(300) NOT NULL,
  CONTENT TEXT,
  ITEM_NAME VARCHAR(500) NOT NULL,
  CATEGORY_ID BIGINT,
  CATEGORY_MAIN VARCHAR(100),
  CATEGORY_SUB VARCHAR(100),
  COLOR_NAME VARCHAR(100),
  LOST_AT DATETIME NOT NULL,
  LOST_AREA VARCHAR(100),
  LOST_PLACE VARCHAR(500) NOT NULL,
  CONTACT VARCHAR(100),
  STATUS VARCHAR(30) NOT NULL DEFAULT 'WAITING',
  IS_DELETED BOOLEAN NOT NULL DEFAULT FALSE,
  REGDATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  MODDATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

  CONSTRAINT FK_LOST_ITEM_USER
    FOREIGN KEY (USER_NO) REFERENCES USERS(USER_NO),

  CONSTRAINT FK_LOST_ITEM_CATEGORY
    FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORY(CATEGORY_ID),

  CONSTRAINT CK_LOST_SOURCE
    CHECK (
      (SOURCE_TYPE = 'USER' AND USER_NO IS NOT NULL AND ATC_ID IS NULL)
      OR
      (SOURCE_TYPE = 'POLICE' AND ATC_ID IS NOT NULL)
    ),

  CONSTRAINT CK_LOST_ITEM_STATUS
    CHECK (STATUS IN ('WAITING', 'FOUND')),

  UNIQUE KEY UK_POLICE_LOST_ITEM (ATC_ID),
  INDEX IDX_LOST_SEARCH (SOURCE_TYPE, CATEGORY_MAIN, LOST_AT, STATUS),
  INDEX IDX_LOST_USER (USER_NO),
  INDEX IDX_LOST_ATC_ID (ATC_ID)
);

CREATE TABLE IF NOT EXISTS LOST_ITEM_IMAGE (
  IMAGE_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  LOST_ID BIGINT NOT NULL,
  ORIGINAL_NAME VARCHAR(255),
  STORED_NAME VARCHAR(255) NOT NULL,
  IMAGE_URL VARCHAR(500) NOT NULL,
  CONTENT_TYPE VARCHAR(100),
  FILE_SIZE BIGINT,
  SORT_ORDER INT NOT NULL DEFAULT 0,
  REGDATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

  CONSTRAINT FK_LOST_IMAGE_ITEM
    FOREIGN KEY (LOST_ID) REFERENCES LOST_ITEM(LOST_ID)
    ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS FOUND_ITEM (
  FOUND_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  USER_NO BIGINT,
  SOURCE_TYPE VARCHAR(30) NOT NULL DEFAULT 'USER',
  ATC_ID VARCHAR(20),
  FD_SN INT,
  TITLE VARCHAR(300),
  CONTENT TEXT,
  ITEM_NAME VARCHAR(200) NOT NULL,
  CATEGORY_ID BIGINT,
  CATEGORY_MAIN VARCHAR(100),
  CATEGORY_SUB VARCHAR(100),
  COLOR_NAME VARCHAR(100),
  FOUND_AT DATETIME NOT NULL,
  FOUND_AREA VARCHAR(100),
  FOUND_PLACE VARCHAR(255),
  KEEP_PLACE VARCHAR(255),
  CONTACT VARCHAR(100),
  CUSTODY_STATUS VARCHAR(50),
  RECEIVE_TYPE VARCHAR(50),
  MANAGE_NO VARCHAR(100),
  SERIAL_NO VARCHAR(100),
  MODEL_CODE VARCHAR(100),
  IMEI VARCHAR(100),
  OWNER_NAME VARCHAR(100),
  STATUS VARCHAR(30) NOT NULL DEFAULT 'KEEPING',
  IS_DELETED BOOLEAN NOT NULL DEFAULT FALSE,
  REGDATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  MODDATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

  CONSTRAINT FK_FOUND_ITEM_USER
    FOREIGN KEY (USER_NO) REFERENCES USERS(USER_NO),

  CONSTRAINT FK_FOUND_ITEM_CATEGORY
    FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORY(CATEGORY_ID),

  CONSTRAINT CK_FOUND_SOURCE
    CHECK (
      (SOURCE_TYPE = 'USER' AND USER_NO IS NOT NULL AND ATC_ID IS NULL AND FD_SN IS NULL)
      OR
      (SOURCE_TYPE = 'POLICE' AND ATC_ID IS NOT NULL AND FD_SN IS NOT NULL)
    ),

  CONSTRAINT CK_FOUND_ITEM_STATUS
    CHECK (STATUS IN ('KEEPING', 'RETURNED')),

  UNIQUE KEY UK_POLICE_FOUND_ITEM (ATC_ID, FD_SN),
  INDEX IDX_FOUND_SEARCH (SOURCE_TYPE, CATEGORY_MAIN, FOUND_AT, STATUS),
  INDEX IDX_FOUND_USER (USER_NO),
  INDEX IDX_FOUND_ATC_ID (ATC_ID)
);

UPDATE LOST_ITEM SET STATUS = 'WAITING' WHERE STATUS = 'MATCHING';
UPDATE FOUND_ITEM SET STATUS = 'KEEPING' WHERE STATUS = 'MATCHING';

CREATE TABLE IF NOT EXISTS FOUND_ITEM_IMAGE (
  IMAGE_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  FOUND_ID BIGINT NOT NULL,
  ORIGINAL_NAME VARCHAR(255),
  STORED_NAME VARCHAR(255),
  IMAGE_URL VARCHAR(600) NOT NULL,
  CONTENT_TYPE VARCHAR(100),
  FILE_SIZE BIGINT,
  SORT_ORDER INT NOT NULL DEFAULT 0,
  REGDATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

  CONSTRAINT FK_FOUND_IMAGE_ITEM
    FOREIGN KEY (FOUND_ID) REFERENCES FOUND_ITEM(FOUND_ID)
    ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS ANIMAL_REPORT (
  REPORT_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  USER_NO BIGINT,
  SOURCE_TYPE VARCHAR(40) NOT NULL DEFAULT 'USER',
  API_PROVIDER VARCHAR(50),
  EXTERNAL_ID VARCHAR(120),
  RAW_PAYLOAD TEXT,
  SYNCED_AT DATETIME,
  REPORT_TYPE VARCHAR(20) NOT NULL,
  STATUS VARCHAR(30) NOT NULL DEFAULT 'OPEN',
  TITLE VARCHAR(300),
  EVENT_DATE DATE NOT NULL,
  EVENT_TIME TIME,
  REGION_AREA_ID BIGINT,
  REGION_NAME VARCHAR(100) NOT NULL,
  DETAIL_PLACE VARCHAR(500) NOT NULL,
  CONTACT_PHONE VARCHAR(100),
  CONTACT_PUBLIC BOOLEAN NOT NULL DEFAULT TRUE,
  SIGHTING_CARE_STATUS VARCHAR(30),
  ANIMAL_TYPE VARCHAR(20) NOT NULL,
  BREED_NAME VARCHAR(100),
  GENDER VARCHAR(20) NOT NULL DEFAULT 'UNKNOWN',
  NEUTERED_STATUS VARCHAR(30) NOT NULL DEFAULT 'UNKNOWN',
  AGE_VALUE INT,
  AGE_UNIT VARCHAR(20),
  WEIGHT_KG DECIMAL(5,2),
  FUR_COLOR VARCHAR(100),
  DISTINCTIVE_MARKS VARCHAR(1000),
  CONTENT TEXT,
  VIEW_COUNT INT NOT NULL DEFAULT 0,
  IS_DELETED BOOLEAN NOT NULL DEFAULT FALSE,
  REGDATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  MODDATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

  CONSTRAINT FK_ANIMAL_REPORT_USER
    FOREIGN KEY (USER_NO) REFERENCES USERS(USER_NO),

  CONSTRAINT FK_ANIMAL_REPORT_REGION
    FOREIGN KEY (REGION_AREA_ID) REFERENCES AREA(AREA_ID),

  CONSTRAINT CK_ANIMAL_REPORT_TYPE
    CHECK (REPORT_TYPE IN ('MISSING', 'SIGHTING')),

  CONSTRAINT CK_ANIMAL_REPORT_SOURCE
    CHECK (SOURCE_TYPE IN ('USER', 'ANIMAL_LOSS_API', 'ANIMAL_PROTECTION_API')),

  CONSTRAINT CK_ANIMAL_REPORT_SOURCE_KEY
    CHECK (
      (SOURCE_TYPE = 'USER' AND USER_NO IS NOT NULL)
      OR
      (SOURCE_TYPE IN ('ANIMAL_LOSS_API', 'ANIMAL_PROTECTION_API') AND EXTERNAL_ID IS NOT NULL)
    ),

  CONSTRAINT CK_ANIMAL_REPORT_STATUS
    CHECK (STATUS IN ('OPEN', 'MATCHING', 'RESOLVED', 'CLOSED')),

  CONSTRAINT CK_ANIMAL_REPORT_CARE_STATUS
    CHECK (SIGHTING_CARE_STATUS IS NULL OR SIGHTING_CARE_STATUS IN ('NONE', 'PROTECTING', 'TRANSFERRED', 'UNKNOWN')),

  CONSTRAINT CK_ANIMAL_REPORT_ANIMAL_TYPE
    CHECK (ANIMAL_TYPE IN ('DOG', 'CAT', 'OTHER')),

  CONSTRAINT CK_ANIMAL_REPORT_GENDER
    CHECK (GENDER IN ('MALE', 'FEMALE', 'UNKNOWN')),

  CONSTRAINT CK_ANIMAL_REPORT_NEUTERED
    CHECK (NEUTERED_STATUS IN ('NEUTERED', 'NOT_NEUTERED', 'UNKNOWN')),

  CONSTRAINT CK_ANIMAL_REPORT_AGE_UNIT
    CHECK (AGE_UNIT IS NULL OR AGE_UNIT IN ('MONTH', 'YEAR', 'UNKNOWN')),

  INDEX IDX_ANIMAL_REPORT_LIST (REPORT_TYPE, STATUS, EVENT_DATE DESC, REPORT_ID DESC),
  UNIQUE KEY UK_ANIMAL_PUBLIC_API (API_PROVIDER, EXTERNAL_ID),
  INDEX IDX_ANIMAL_REPORT_REGION (REGION_AREA_ID, REPORT_TYPE, STATUS, EVENT_DATE DESC),
  INDEX IDX_ANIMAL_REPORT_MATCH_CANDIDATE (ANIMAL_TYPE, EVENT_DATE, REGION_AREA_ID, STATUS),
  INDEX IDX_ANIMAL_REPORT_SOURCE (SOURCE_TYPE, EVENT_DATE DESC),
  INDEX IDX_ANIMAL_REPORT_USER (USER_NO)
);

CREATE TABLE IF NOT EXISTS ANIMAL_REPORT_IMAGE (
  IMAGE_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  REPORT_ID BIGINT NOT NULL,
  ORIGINAL_NAME VARCHAR(255),
  STORED_NAME VARCHAR(255) NOT NULL,
  IMAGE_URL VARCHAR(600) NOT NULL,
  CONTENT_TYPE VARCHAR(100),
  FILE_SIZE BIGINT,
  SORT_ORDER INT NOT NULL DEFAULT 0,
  REGDATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

  CONSTRAINT FK_ANIMAL_REPORT_IMAGE_REPORT
    FOREIGN KEY (REPORT_ID) REFERENCES ANIMAL_REPORT(REPORT_ID)
    ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS ANIMAL_REPORT_IMAGE_EMBEDDING (
  EMBEDDING_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  REPORT_ID BIGINT NOT NULL,
  IMAGE_ID BIGINT NOT NULL,
  VECTOR_BLOB LONGBLOB NOT NULL,
  MODEL_NAME VARCHAR(200) NOT NULL,
  CROP_TYPE VARCHAR(40) NOT NULL DEFAULT 'ORIGINAL_FALLBACK',
  CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

  CONSTRAINT FK_ANIMAL_EMBEDDING_REPORT
    FOREIGN KEY (REPORT_ID) REFERENCES ANIMAL_REPORT(REPORT_ID)
    ON DELETE CASCADE,

  CONSTRAINT FK_ANIMAL_EMBEDDING_IMAGE
    FOREIGN KEY (IMAGE_ID) REFERENCES ANIMAL_REPORT_IMAGE(IMAGE_ID)
    ON DELETE CASCADE,

  UNIQUE KEY UK_ANIMAL_REPORT_EMBEDDING (REPORT_ID)
);

CREATE TABLE IF NOT EXISTS ANIMAL_REPORT_MATCH (
  MATCH_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  MISSING_REPORT_ID BIGINT NOT NULL,
  SIGHTING_REPORT_ID BIGINT NOT NULL,
  MATCH_SCORE DECIMAL(5,2),
  RULE_SCORE DECIMAL(5,2),
  SEMANTIC_SCORE DECIMAL(5,2),
  FINAL_SCORE DECIMAL(5,2),
  MATCH_REASONS TEXT,
  MATCH_VERSION VARCHAR(100),
  MODEL_NAME VARCHAR(100),
  MATCH_STATUS VARCHAR(30) NOT NULL DEFAULT 'CANDIDATE',
  REGDATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  MODDATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

  CONSTRAINT FK_ANIMAL_MATCH_MISSING_REPORT
    FOREIGN KEY (MISSING_REPORT_ID) REFERENCES ANIMAL_REPORT(REPORT_ID),

  CONSTRAINT FK_ANIMAL_MATCH_SIGHTING_REPORT
    FOREIGN KEY (SIGHTING_REPORT_ID) REFERENCES ANIMAL_REPORT(REPORT_ID),

  CONSTRAINT CK_ANIMAL_MATCH_STATUS
    CHECK (MATCH_STATUS IN ('CANDIDATE', 'CONFIRMED', 'REJECTED')),

  UNIQUE KEY UK_ANIMAL_MATCH_REPORTS (MISSING_REPORT_ID, SIGHTING_REPORT_ID),
  INDEX IDX_ANIMAL_MATCH_MISSING (MISSING_REPORT_ID, MATCH_STATUS, FINAL_SCORE),
  INDEX IDX_ANIMAL_MATCH_SIGHTING (SIGHTING_REPORT_ID, MATCH_STATUS, FINAL_SCORE)
);

CREATE TABLE IF NOT EXISTS MISSING_PERSON_REPORT (
  REPORT_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  USER_NO BIGINT,
  SOURCE_TYPE VARCHAR(30) NOT NULL DEFAULT 'USER',
  EXTERNAL_ID VARCHAR(100),
  API_PROVIDER VARCHAR(50),
  RAW_PAYLOAD MEDIUMTEXT,
  SYNCED_AT DATETIME,
  PERSON_NAME VARCHAR(100),
  GENDER VARCHAR(30),
  AGE INT NOT NULL,
  NATIONALITY VARCHAR(100) NOT NULL,
  OCCURRED_AT DATETIME NOT NULL,
  OCCURRED_PLACE VARCHAR(500) NOT NULL,
  HEIGHT_CM INT,
  WEIGHT_KG DECIMAL(5,1),
  BODY_TYPE VARCHAR(100) NOT NULL,
  FACE_SHAPE VARCHAR(100) NOT NULL,
  HAIR_COLOR VARCHAR(100) NOT NULL,
  HAIR_STYLE VARCHAR(100) NOT NULL,
  CLOTHING VARCHAR(1000) NOT NULL,
  SEARCH_CONTENT VARCHAR(768),
  STATUS VARCHAR(30) NOT NULL DEFAULT 'OPEN',
  IS_DELETED BOOLEAN NOT NULL DEFAULT FALSE,
  REGDATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  MODDATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

  CONSTRAINT FK_MISSING_PERSON_USER
    FOREIGN KEY (USER_NO) REFERENCES USERS(USER_NO),

  CONSTRAINT CK_MISSING_PERSON_STATUS
    CHECK (STATUS IN ('OPEN', 'FOUND', 'CLOSED')),

  CONSTRAINT CK_MISSING_PERSON_SOURCE
    CHECK (
      (SOURCE_TYPE = 'USER' AND USER_NO IS NOT NULL AND EXTERNAL_ID IS NULL)
      OR
      (SOURCE_TYPE = 'PUBLIC_API' AND EXTERNAL_ID IS NOT NULL)
    ),

  UNIQUE KEY UK_MISSING_PERSON_PUBLIC_API (API_PROVIDER, EXTERNAL_ID),
  INDEX IDX_MISSING_PERSON_LIST (SOURCE_TYPE, STATUS, OCCURRED_AT DESC, REPORT_ID DESC),
  INDEX IDX_MISSING_PERSON_USER (USER_NO),
  INDEX IDX_MISSING_PERSON_SEARCH (SEARCH_CONTENT)
);

CREATE TABLE IF NOT EXISTS MISSING_PERSON_IMAGE (
  IMAGE_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  REPORT_ID BIGINT NOT NULL,
  ORIGINAL_NAME VARCHAR(255),
  STORED_NAME VARCHAR(255) NOT NULL,
  IMAGE_URL VARCHAR(600) NOT NULL,
  CONTENT_TYPE VARCHAR(100),
  FILE_SIZE BIGINT,
  SORT_ORDER INT NOT NULL DEFAULT 0,
  REGDATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

  CONSTRAINT FK_MISSING_PERSON_IMAGE_REPORT
    FOREIGN KEY (REPORT_ID) REFERENCES MISSING_PERSON_REPORT(REPORT_ID)
    ON DELETE CASCADE,

  INDEX IDX_MISSING_PERSON_IMAGE_REPORT (REPORT_ID, SORT_ORDER, IMAGE_ID)
);

CREATE TABLE IF NOT EXISTS ITEM_MATCH (
  MATCH_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  LOST_ID BIGINT NOT NULL,
  FOUND_ID BIGINT NOT NULL,
  MATCH_SCORE DECIMAL(5,2),
  RULE_SCORE DECIMAL(5,2),
  SEMANTIC_SCORE DECIMAL(5,2),
  FINAL_SCORE DECIMAL(5,2),
  MATCH_REASONS TEXT,
  MATCH_VERSION VARCHAR(100),
  MODEL_NAME VARCHAR(100),
  MATCH_STATUS VARCHAR(30) NOT NULL DEFAULT 'CANDIDATE',
  REGDATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  MODDATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

  CONSTRAINT FK_MATCH_LOST
    FOREIGN KEY (LOST_ID) REFERENCES LOST_ITEM(LOST_ID),

  CONSTRAINT FK_MATCH_FOUND
    FOREIGN KEY (FOUND_ID) REFERENCES FOUND_ITEM(FOUND_ID),

  UNIQUE KEY UK_MATCH_LOST_FOUND (LOST_ID, FOUND_ID)
);

DROP TABLE IF EXISTS KORAIL_STATION_LOCATION;
CREATE TABLE IF NOT EXISTS KORAIL_STATION_LOCATION (
  station_id BIGINT AUTO_INCREMENT PRIMARY KEY,
  line_name VARCHAR(50) NOT NULL,
  station_name VARCHAR(100) NOT NULL,
  latitude DOUBLE NOT NULL,
  longitude DOUBLE NOT NULL,
  exit_count INT,
  INDEX IDX_STATION_LOOKUP (station_name, line_name)
);

CREATE TABLE IF NOT EXISTS KORAIL_LOST_FOUND_CENTER (
  center_id BIGINT AUTO_INCREMENT PRIMARY KEY,
  operator_name VARCHAR(100),
  line_name VARCHAR(50),
  sub_region VARCHAR(100),
  station_name VARCHAR(100) NOT NULL,
  location_details VARCHAR(500),
  operating_hours VARCHAR(200),
  tel_no VARCHAR(50),
  INDEX IDX_LOST_FOUND_STATION (station_name, line_name)
);


CREATE TABLE IF NOT EXISTS INQUIRY (
INQUIRY_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
USER_NO BIGINT,
CATEGORY VARCHAR(20) NOT NULL,
TITLE VARCHAR(200) NOT NULL,
CONTENT TEXT NOT NULL,
STATUS VARCHAR(30) NOT NULL DEFAULT 'UNREAD',
ANSWER TEXT,
ANSWERED_AT DATETIME,
IS_PRIVATE BOOLEAN NOT NULL DEFAULT TRUE,
REGDATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
MODDATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

CONSTRAINT FK_INQUIRY_USER FOREIGN KEY (USER_NO) REFERENCES USERS(USER_NO),
CONSTRAINT CK_INQUIRY_CATEGORY CHECK (CATEGORY IN ('분실물','습득물','서비스','기타')),
CONSTRAINT CK_INQUIRY_STATUS CHECK (STATUS IN ('UNREAD','CHECKING','ANSWERED'))
);

CREATE TABLE IF NOT EXISTS INQUIRY_FILE (
FILE_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
INQUIRY_ID BIGINT NOT NULL,
ORIGINAL_NAME VARCHAR(255) NOT NULL,
STORED_NAME VARCHAR(255) NOT NULL,
FILE_URL VARCHAR(500) NOT NULL,
CONTENT_TYPE VARCHAR(100),
FILE_SIZE BIGINT,
REGDATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

CONSTRAINT FK_INQUIRY_FILE FOREIGN KEY (INQUIRY_ID)
REFERENCES INQUIRY(INQUIRY_ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS FAQ (
FAQ_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
QUESTION VARCHAR(300) NOT NULL,
ANSWER TEXT NOT NULL,
CATEGORY VARCHAR(50),
SORT_ORDER INT NOT NULL DEFAULT 0,
IS_ACTIVE BOOLEAN NOT NULL DEFAULT TRUE,
REGDATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
MODDATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
ON UPDATE CURRENT_TIMESTAMP
);

DROP TABLE IF EXISTS CHAT_MESSAGE;
DROP TABLE IF EXISTS CHAT_ROOM;

CREATE TABLE IF NOT EXISTS CHAT_ROOM (
  ROOM_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  FOUND_ID BIGINT,
  LOST_ID BIGINT,
  INQUIRER_NO BIGINT NOT NULL,
  OWNER_NO BIGINT NOT NULL,
  CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

  CONSTRAINT FK_CHAT_FOUND FOREIGN KEY (FOUND_ID) REFERENCES FOUND_ITEM(FOUND_ID),
  CONSTRAINT FK_CHAT_LOST FOREIGN KEY (LOST_ID) REFERENCES LOST_ITEM(LOST_ID),
  CONSTRAINT FK_CHAT_INQUIRER FOREIGN KEY (INQUIRER_NO) REFERENCES USERS(USER_NO),
  CONSTRAINT FK_CHAT_OWNER FOREIGN KEY (OWNER_NO) REFERENCES USERS(USER_NO)
);

CREATE TABLE IF NOT EXISTS CHAT_MESSAGE (
  MESSAGE_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  ROOM_ID BIGINT NOT NULL,
  SENDER_NO BIGINT NOT NULL,
  CONTENT VARCHAR(1000) NOT NULL,
  MESSAGE_TYPE VARCHAR(20) NOT NULL,
  IS_READ BOOLEAN NOT NULL DEFAULT FALSE,
  FILE_URL VARCHAR(500) NULL,
  FILE_NAME VARCHAR(255) NULL,
  FILE_SIZE BIGINT NULL,
  FILE_GROUP_ID VARCHAR(80) NULL,
  CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

  CONSTRAINT FK_MESSAGE_ROOM FOREIGN KEY (ROOM_ID) REFERENCES CHAT_ROOM(ROOM_ID),
  CONSTRAINT FK_MESSAGE_SENDER FOREIGN KEY (SENDER_NO) REFERENCES USERS(USER_NO)
);

CREATE TABLE IF NOT EXISTS NOTICE (
NOTICE_ID BIGINT PRIMARY KEY AUTO_INCREMENT,
TITLE VARCHAR(200) NOT NULL,
CONTENT TEXT NOT NULL,
CATEGORY VARCHAR(50) NOT NULL,
IS_DELETED CHAR(1) DEFAULT 'N',
CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
UPDATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
WRITER VARCHAR(50) NOT NULL,
VIEW_COUNT INT DEFAULT 0
);


CREATE TABLE IF NOT EXISTS ITEM_EMBEDDING (
EMBEDDING_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
ITEM_TYPE VARCHAR(10) NOT NULL,
ITEM_ID BIGINT NOT NULL,
EMBEDDING_TEXT VARCHAR(1000) NOT NULL,
TEXT_HASH VARCHAR(64) NOT NULL,
MODEL_NAME VARCHAR(200) NOT NULL,
VECTOR_BLOB LONGBLOB NOT NULL,
CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
UPDATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
UNIQUE KEY UK_ITEM_EMBEDDING (ITEM_TYPE, ITEM_ID)
);

CREATE TABLE IF NOT EXISTS GUIDE (
GUIDE_ID BIGINT PRIMARY KEY AUTO_INCREMENT,
TITLE VARCHAR(200) NOT NULL,
CONTENT TEXT NOT NULL,
CATEGORY VARCHAR(50) NOT NULL,
IS_DELETED CHAR(1) DEFAULT 'N',
CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
UPDATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
WRITER VARCHAR(50) NOT NULL
);
DROP TABLE IF EXISTS GUIDE;

CREATE TABLE IF NOT EXISTS POST_REPORT (
  REPORT_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  REPORTER_NO BIGINT NOT NULL,
  TARGET_TYPE VARCHAR(30) NOT NULL,
  TARGET_ID BIGINT NOT NULL,
  TARGET_OWNER_NO BIGINT NOT NULL,
  TARGET_TITLE VARCHAR(300) NOT NULL,
  TARGET_URL VARCHAR(500) NOT NULL,
  REASON_TYPE VARCHAR(30) NOT NULL,
  REASON_DETAIL VARCHAR(1000),
  STATUS VARCHAR(30) NOT NULL DEFAULT 'PENDING',
  ADMIN_MEMO VARCHAR(1000),
  HANDLER_NO BIGINT,
  CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  HANDLED_AT DATETIME,

  CONSTRAINT FK_POST_REPORT_REPORTER
    FOREIGN KEY (REPORTER_NO) REFERENCES USERS(USER_NO),

  CONSTRAINT FK_POST_REPORT_HANDLER
    FOREIGN KEY (HANDLER_NO) REFERENCES USERS(USER_NO),

  CONSTRAINT CK_POST_REPORT_TARGET_TYPE
    CHECK (TARGET_TYPE IN ('LOST_ITEM', 'FOUND_ITEM', 'ANIMAL_REPORT', 'MISSING_PERSON')),

  CONSTRAINT CK_POST_REPORT_REASON_TYPE
    CHECK (REASON_TYPE IN ('SPAM', 'FRAUD', 'INAPPROPRIATE', 'PRIVACY', 'WRONG_INFO', 'ETC')),

  CONSTRAINT CK_POST_REPORT_STATUS
    CHECK (STATUS IN ('PENDING', 'REVIEWING', 'RESOLVED', 'REJECTED')),

  UNIQUE KEY UK_REPORT_DUPLICATE (REPORTER_NO, TARGET_TYPE, TARGET_ID),
  INDEX IDX_POST_REPORT_STATUS (STATUS, CREATED_AT),
  INDEX IDX_POST_REPORT_TARGET (TARGET_TYPE, TARGET_ID)
);
