USE dogo;

SET @has_crop_type := (
  SELECT COUNT(*)
  FROM information_schema.COLUMNS
  WHERE TABLE_SCHEMA = DATABASE()
    AND TABLE_NAME = 'ANIMAL_REPORT_IMAGE_EMBEDDING'
    AND COLUMN_NAME = 'CROP_TYPE'
);

SET @sql := IF(
  @has_crop_type = 0,
  'ALTER TABLE ANIMAL_REPORT_IMAGE_EMBEDDING ADD COLUMN CROP_TYPE VARCHAR(40) NOT NULL DEFAULT ''LEGACY_ORIGINAL'' AFTER MODEL_NAME',
  'SELECT ''CROP_TYPE already exists'' AS message'
);
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

ALTER TABLE ANIMAL_REPORT_IMAGE_EMBEDDING
  ALTER COLUMN CROP_TYPE SET DEFAULT 'ORIGINAL_FALLBACK';

SET @has_image_fk := (
  SELECT COUNT(*)
  FROM information_schema.KEY_COLUMN_USAGE
  WHERE TABLE_SCHEMA = DATABASE()
    AND TABLE_NAME = 'ANIMAL_REPORT_IMAGE_EMBEDDING'
    AND COLUMN_NAME = 'IMAGE_ID'
    AND REFERENCED_TABLE_NAME = 'ANIMAL_REPORT_IMAGE'
    AND REFERENCED_COLUMN_NAME = 'IMAGE_ID'
);

SET @sql := IF(
  @has_image_fk = 0,
  'ALTER TABLE ANIMAL_REPORT_IMAGE_EMBEDDING ADD CONSTRAINT FK_ANIMAL_EMBEDDING_IMAGE FOREIGN KEY (IMAGE_ID) REFERENCES ANIMAL_REPORT_IMAGE(IMAGE_ID) ON DELETE CASCADE',
  'SELECT ''FK_ANIMAL_EMBEDDING_IMAGE already exists'' AS message'
);
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;
