package com.example.dogo.dto.animal;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalTime;
import java.util.List;

public record AnimalReportDetailView(
		Long id,
		String reportType,
		String reportTypeLabel,
		String status,
		String statusLabel,
		String title,
		LocalDate eventDate,
		LocalTime eventTime,
		String regionName,
		String detailPlace,
		String locationSummary,
		String contactPhone,
		boolean contactPublic,
		String displayContact,
		String sightingCareStatus,
		String sightingCareStatusLabel,
		String animalType,
		String animalTypeLabel,
		String breedName,
		String gender,
		String genderLabel,
		String neuteredStatus,
		String neuteredStatusLabel,
		Integer ageValue,
		String ageUnit,
		String ageUnitLabel,
		BigDecimal weightKg,
		String ageDisplay,
		String weightDisplay,
		String furColor,
		String distinctiveMarks,
		String content,
		String displayContent,
		String shelterName,
		String shelterAddress,
		String authorityName,
		String noticeNo,
		String noticePeriod,
		int viewCount,
		List<String> imageUrls,
		Long userNo
) {
}
